name: Lint go

on:
  pull_request:
    paths:
      - '**.go'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v3
